# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Load React Native Pod helpers
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

use_frameworks! :linkage => :static

target 'NewTesting' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
